VAGRANTFILE_API_VERSION = "2"
 
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  config.vm.define "VM1" do |vm1|
    vm1.vm.box = "ubuntu/focal64"
    vm1.vm.provider :virtualbox do |vb|
      vb.name = "VM1-net-gateway"
    end
    vm1.vm.hostname = "vm1"

    vm1.vm.network "private_network", ip: "192.168.12.10",
      virtualbox__intnet: "isolated"

    vm1.vm.provision :shell, path: "bootstrap.sh"

    vm1.vm.provision "shell", run: "always", inline: "systemd-resolve --interface enp0s8 --set-dns 192.168.12.10 --set-domain localnet"
    vm1.vm.provision "shell", run: "always", inline: <<-SHELL
      # enable routing
      sysctl -w net.ipv4.ip_forward=1
      iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE
      # iptables -A FORWARD -i enp0s8 -o enp0s3 -j ACCEPT
      # iptables -A FORWARD -i enp0s3 -o enp0s8 -m state --state RELATED,ESTABLISHED -j ACCEPT
    SHELL
  end
 

  config.vm.define "VM2" do |vm2|
    vm2.vm.box = "ubuntu/focal64"
    vm2.vm.provider :virtualbox do |vb|
      vb.name = "VM2-net-gateway"
    end
    vm2.vm.hostname = "vm2"

    vm2.vm.network "private_network", type: "dhcp", mac: "080027fae675",
      virtualbox__intnet: "isolated"
    
    vm2.vm.provision :shell, path: "bootstrap.sh"
    #vm2.vm.provision "shell", run: "always", inline: "ip route del default"
    #vm2.vm.provision "shell", run: "always", inline: "ip route add default via 192.168.12.10"
  end


  config.vm.define "VM3" do |vm3|
    vm3.vm.box = "ubuntu/focal64"
    vm3.vm.provider :virtualbox do |vb|
      vb.name = "VM3-net-gateway"
    end
    vm3.vm.hostname = "vm3"

    vm3.vm.network "private_network", type: "dhcp", mac: "08002752b7e0",
      virtualbox__intnet: "isolated"

    vm3.vm.provision :shell, path: "bootstrap.sh"
    #vm3.vm.provision "shell", run: "always", inline: "ip route del default"
    #vm3.vm.provision "shell", run: "always", inline: "ip route add default via 192.168.12.10"
  end

end