---
- name: Deploy Jenkins master server
#- hosts: "{{ passed_in_hosts }}"
  hosts: master

  vars:
    ansible_python_interpreter: /usr/bin/python3.7
    hostname: jenkins
    jenkins_home_backup_path: ./templates/remote/jenkins/
    jenkins_home_path: /var/lib/jenkins
    packages:
      - wget
      - java-11-amazon-corretto-headless
      - git

  pre_tasks:
    - name: Wait for EC2 instance to become available
      wait_for_connection:
        timeout: 300

    - name: Set up hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"
  
  roles:
    - mirom.software-install
    - mirom.jenkins
    - mirom.jenkins-home
