---
- name: Deploy Jenkins Slave node
  hosts: jenkins-slave
  become: yes
  remote_user: ec2-user

  vars:
    ansible_python_interpreter: /usr/bin/python3.7
    hostname: slave
    packages:
      - wget
      - java-11-amazon-corretto-headless
      - git
      - python3-pip

  pre_tasks:
    - name: Wait for EC2 instance to become available
      wait_for_connection:
        timeout: 300

    - name: Set up hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"
  
  roles:
    - mirom.software-install
    - mirom.docker
    - mirom.ansible
    - mirom.jenkins-slave

  post_tasks:
    - name: Restart Jenkins master server
      vars:
        master: "{{ master_ip }}"
      shell: 'cat /home/ec2-user/node.xml | java -jar /home/ec2-user/jenkins-cli.jar -auth @/home/ec2-user/jenkins_auth -s http://{{ master }}:8080/ restart'
