---
- name: Deploy Apache2 Web Server
  hosts: webserver

  vars:
    firewall_allowed_tcp_ports:
      - "22"
      - "80"
      - "443"
      - "8080"

  roles:
    - geerlingguy.firewall
    - geerlingguy.apache