VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/focal64"

  config.vm.define "MYSQL" do |mysql|
    mysql.vm.box = "ubuntu/focal64"
    mysql.vm.provider :virtualbox do |vb|
      vb.name = "db-mysql"
    end
    mysql.vm.hostname = "mysql-vm"

    mysql.vm.network "private_network", ip: "192.168.56.10"
    mysql.vm.network "forwarded_port", guest: 3306, host: 3306
    mysql.vm.provision :shell, path: "bootstrap.sh"
  end

  config.vm.define "MONGO" do |mongo|
    mongo.vm.box = "ubuntu/focal64"
    mongo.vm.provider :virtualbox do |vb|
      vb.name = "db-mongo"
    end
    mongo.vm.hostname = "mongo-vm"

    mongo.vm.network "private_network", ip: "192.168.56.20"
    mongo.vm.network "forwarded_port", guest: 27017, host: 27017
    mongo.vm.provision :shell, path: "bootstrap.sh"
  end 
end
