VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/focal64"

  config.vm.define "db-server" do |db|
      db.vm.network "private_network", ip: "192.168.12.8"
      db.vm.network "forwarded_port", guest: 3306, host: 3306
      db.vm.provision :shell, path: "bootstrap.sh"
  end
end
