---
- name: Deploy Jenkins Server
  hosts: jenkins

  vars:
    jenkins_admin_password: tustan
    java_packages: java-11-amazon-corretto-headless
    ansible_install_method: pip
    ansible_python_interpreter: /usr/bin/python3.7
    firewall_allowed_tcp_ports:
      - "22"
      - "80"
      - "8080"
    jenkins_plugins:
      - ansicolor
      - publish-over-ssh
      - git
      - github
      - workflow-aggregator
      - credentials
      - pipeline-stage-view


  roles:
    - geerlingguy.firewall
    - geerlingguy.pip
    - geerlingguy.ansible
    - andrewrothstein.terraform
    - geerlingguy.git
    - geerlingguy.java
    - geerlingguy.jenkins
  
  tasks:
    - name: Set server hostname
      ansible.builtin.hostname:
        name: jenkins
        
    - name: Enable jenkins user with SSH
      ansible.builtin.user:
        name: jenkins
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_type: rsa
        ssh_key_file: .ssh/jenkins_server_id_rsa
      register: ssh_public_key
    
    - name: Print Jenkins Server public SSH key
      debug:
        msg: "{{ ssh_public_key  }}"
