---
roles:
  - name: geerlingguy.firewall
  - name: geerlingguy.pip
  - name: geerlingguy.ansible
  - name: geerlingguy.java
  - name: geerlingguy.jenkins
  - name: geerlingguy.apache
  - name: andrewrothstein.terraform