VAGRANTFILE_API_VERSION = "2"

$sshpass = <<-SCRIPT
  # enable ssh password
  sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config    
  systemctl restart sshd.service
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  config.vm.define "SRV1" do |srv1|
    srv1.vm.box = "ubuntu/focal64"
    srv1.vm.provider :virtualbox do |vb|
      vb.name = "Server-1"
    end
    srv1.vm.hostname = "Server-1"

    srv1.vm.network "private_network", ip: "10.81.5.1",
      virtualbox__intnet: "Net2"
    srv1.vm.network "private_network", ip: "10.8.81.1",
      virtualbox__intnet: "Net3"

    # srv1.vm.provision :shell, path: "bootstrap.sh"
  end
 

  config.vm.define "CLT1" do |clt1|
    clt1.vm.box = "ubuntu/focal64"
    clt1.vm.provider :virtualbox do |vb|
      vb.name = "Client-1"
    end
    clt1.vm.hostname = "Client-1"

    # clt1.vm.network "private_network", ip: "10.81.5.254", mac: "080027fae675",
    #   virtualbox__intnet: "Net2"
    clt1.vm.network "private_network", type: "dhcp", mac: "080027fae675",
      virtualbox__intnet: "Net2"
    clt1.vm.network "private_network", ip: "172.16.5.1",
      virtualbox__intnet: "Net4"
    
    # clt1.vm.provision :shell, path: "bootstrap.sh"
    # clt1.vm.provision :shell, inline: $sshpass
  end


  config.vm.define "CLT2" do |clt2|
    clt2.vm.box = "centos/7"
    clt2.vm.provider :virtualbox do |vb|
      vb.name = "Client-2"
    end
    clt2.vm.hostname = "Client-2"

    # clt2.vm.network "private_network", ip: "10.8.81.254", mac: "08002752b7e0",
    #   virtualbox__intnet: "Net3"
    clt2.vm.network "private_network", type: "dhcp", mac: "08002752b7e0",
      virtualbox__intnet: "Net3"
    clt2.vm.network "private_network", ip: "172.16.5.254",
      virtualbox__intnet: "Net4"

    # clt2.vm.provision :shell, path: "bootstrap.sh"
    # clt2.vm.provision :shell, inline: $sshpass
  end

  config.vm.provision :shell, path: "bootstrap.sh"

end