#!/usr/bin/env bash
#
# NAME
#    backup - Make backup of files in a given directory
#
# SYNOPSIS
#    backup <sourcedir> <destdir>
#
# DESCRIPTION
#    Sync files between source and destination directories.
#   
#    <sourcedir> and <destdir>
#           Relative or absolute path to a directory
#    --help
#           Output this documentation.
#
# EXAMPLES
#    backup /home/user/sourcedir /home/user/backup/destdir
#
################################################################################

usage() {
    while IFS= read -r line || [[ -n "$line" ]]
    do
        case "$line" in
            '#!'*) # Shebang line
                ;;
            ''|'##'*|[!#]*) # End of Help block
                exit "${1:-0}"
                ;;
            *) # Help line
                printf '%s\n' "${line:1}"
                ;;
        esac
    done < "$0"
}


# printlog <operation type> <target>
printlog() {
    echo "[$(date "+%Y/%m/%d-%H:%M:%S")] $1 $2" | tee -a "$logfile" 
}


# dircmp <srcdir> <dstdir> <filelist>
dircmp () {
    local list=$3
    local file
    for file in $list; do
        if [ -d "$1$file" ] && ! [ -d "$2$file" ]; then
            echo "$file"
        fi
    done
}


# filecmp <srcdir> <dstdir> <filelist>
filecmp () {
    local list=$3
    local file
    for file in $list; do
        if [ -f "$1$file" ]; then
            cmp "$1$file" "$2$file" &> /dev/null
            if [ $? -ne 0 ]; then
                echo "$file"
            fi
        fi
    done
}


# dobackup <scrdir> <dstdir>
dobackup () {
    local list
    local filename

    list=$(tree -if --noreport "$1" | sed "s!$1!!")

    dircmp "$1" "$2" "$list" | while read filename; do
        printlog "Add dir" "$filename"
        mkdir "$2$filename"
    done
    filecmp "$1" "$2" "$list" | while read filename; do
        printlog "Copy file" "$filename"
        cp -a "$1$filename" "$2$filename"
    done

    list=$(tree -if --noreport "$2" | sed "s!$2!!")

    filecmp "$2" "$1" "$list" | while read filename; do
        printlog "Remove file" "$filename"
        rm -f "$2$filename"
    done
    dircmp "$2" "$1" "$list" | while read filename; do
        printlog "Remove dir" "$filename"
        rmdir "$2$filename"
    done
}



if [[ $# -lt 2 ]]; then
    usage 13
fi

# Variables initialization
logdir=/var/log/backup
logfile=${logdir}/backup.log

srcdir="${1%/}"
dstdir="${2%/}"

# Create directories
if ! [ -d "$dstdir" ]; then mkdir "$dstdir"; fi
if ! [ -d "$logdir" ]; then mkdir "$logdir"; fi

dobackup "$srcdir" "$dstdir"