#!/usr/bin/env bash
#
# NAME
#    logstat - Get statistics from given apache log file
#
# SYNOPSIS
#    logstat <filename.log>
#
################################################################################

usage() {
    while IFS= read -r line || [[ -n "$line" ]]
    do
        case "$line" in
            '#!'*) # Shebang line
                ;;
            ''|'##'*|[!#]*) # End of Help block
                exit "${1:-0}"
                ;;
            *) # Help line
                printf '%s\n' "${line:1}"
                ;;
        esac
    done < "$0"
}


if [[ $# -lt 1 ]]; then
    usage 13
fi

options=("From which ip were the most requests?" \
         "What is the most requested page?" \
         "How many requests were there from each ip?" \
         "What non-existent pages were clients referred to?" \
         "What time did site get the most requests?" \
         "What search bots have accessed the site? (UA + IP)"
)
PS3="Please enter your choice: "
select opt in "${options[@]}"; do
    case $REPLY in
        1)
            awk '{ print $1 }' $1 | sort -g | uniq -c | sort -nr | head -1 | awk '{ print $2 }'
            break
        ;;
        2)
            awk '{ print $7 }' $1 | sort | uniq -c | sort -nr | head -1 | awk '{ print $2 }'
            break
        ;;
        3)
            awk '{ print $1 }' $1 | sort -g | uniq -c | sort -nr
            break
        ;;
        4)
            awk '$9 == "404" { print $7 }' $1 | sort | uniq
            break
        ;;
        5)
            awk '{ print $4 }' $1 | cut -d":" -f2,3 | uniq -c | sort -nr | head -1 | awk '{ print $2 }'
            break
        ;;
        6)
            awk -F'"' '{ print $1 $(NF-1) }' $1 | grep -iE "(Google|bot|fetcher|analyzer|scraper|crawler)" | sed 's/\- \[[^]]*\] //g' | sort | uniq
            break
        ;;
        *) echo "Invalid option $REPLY";;
    esac
    
done




